apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
        # Define the environment variable
        - name: DB
          valueFrom:
            configMapKeyRef:
              name: example-configmap  # El nombre del ConfigMap
              key: database # La clave. El valor asociado a esta clave se va a asignar a DB
        - name: USER
          valueFrom:
            secretKeyRef:
               name: db-creds # El nombre del Secret
               key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
               name: db-creds
               key: password
    command: ["/bin/sh"]
    args: ["-c","echo user: $USER, password: $PASSWORD, db: $DB"]